name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to the branch you use for production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7  # Match the Ruby version to your local development environment

    - name: Build and deploy
      env:
        JEKYLL_ENV: production
      run: |
        gem install bundler
        bundle install
        bundle exec jekyll build
        touch ./_site/.nojekyll  # Prevents GitHub from processing Jekyll files

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
